[package]
name = "rsutils"
version = "0.1.0"
authors = ["LonelyPale <lonelypale@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "cmd/math",
]
